In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import tree
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import mean_squared_error

C:\Users\hp\anaconda3\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.24.3
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

In [2]:
df = pd.read_csv("C:\\Users\\hp\\Downloads\\fir_deatils_with_date_time.csv")
df

C:\Users\hp\AppData\Local\Temp\ipykernel_7424\964079572.py:1: DtypeWarning: Columns (19,20) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("C:\\Users\\hp\\Downloads\\fir_deatils_with_date_time.csv")

,District_Name,UnitName,FIRNo,RI,Year,Month,Offence_From_Date,Offence_To_Date,FIR_Reg_DateTime,FIR_Date,...,Crime_No,Day_Offence_From,Hour_Offence_From,Minute_Offence_From,Day_Offence_To,Hour_Offence_To,Minute_Offence_To,Day_FIR_Reg,Hour_FIR_Reg,Minute_FIR_Reg
0,Bagalkot,Amengad PS,0001/2016,1,2016,1,2015-12-27 12:00:00,2015-12-27 12:05:00,2016-01-05 11:00:00,05/01/2016,...,10470124520160001,27,12,0,27.0,12.0,5.0,5,11,0
1,Bagalkot,Amengad PS,0002/2016,1,2016,1,2016-01-12 17:30:00,2016-01-12 17:35:00,2016-01-12 19:00:00,12/01/2016,...,10470124520160002,12,17,30,12.0,17.0,35.0,12,19,0
2,Bagalkot,Amengad PS,0003/2016,1,2016,1,2016-01-12 17:45:00,2016-01-12 17:50:00,2016-01-12 19:30:00,12/01/2016,...,10470124520160003,12,17,45,12.0,17.0,50.0,12,19,30
3,Bagalkot,Amengad PS,0004/2016,1,2016,1,2016-01-14 21:30:00,2016-01-14 21:35:00,2016-01-15 14:00:00,15/01/2016,...,10470124520160004,14,21,30,14.0,21.0,35.0,15,14,0
4,Bagalkot,Amengad PS,0005/2016,1,2016,1,2016-01-18 15:00:00,2016-01-18 15:05:00,2016-01-18 19:30:00,18/01/2016,...,10470124520160005,18,15,0,18.0,15.0,5.0,18,19,30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1694186,Yadgir,Yadgiri Women PS,0002/2024,1,2024,1,2024-01-10 05:30:00,2024-01-10 21:30:00,2024-01-11 21:30:00,11/01/2024,...,10978218320240002,10,5,30,10.0,21.0,30.0,11,21,30
1694187,Yadgir,Yadgiri Women PS,0003/2024,1,2024,1,2024-01-19 22:30:00,2024-01-19 22:35:00,2024-01-29 19:30:00,29/01/2024,...,10978218320240003,19,22,30,19.0,22.0,35.0,29,19,30
1694188,Yadgir,Yadgiri Women PS,0004/2024,1,2024,2,2024-02-06 15:42:00,2024-02-06 15:45:00,2024-02-07 17:45:00,07/02/2024,...,10978218320240004,6,15,42,6.0,15.0,45.0,7,17,45
1694189,Yadgir,Yadgiri Women PS,0005/2024,1,2024,2,2024-02-19 12:10:00,2024-02-19 12:15:00,2024-02-24 17:00:00,24/02/2024,...,10978218320240005,19,12,10,19.0,12.0,15.0,24,17,0
1694190,Yadgir,Yadgiri Women PS,0006/2024,1,2024,2,2024-02-26 22:30:00,2024-02-26 22:45:00,2024-02-28 18:30:00,28/02/2024,...,10978218320240006,26,22,30,26.0,22.0,45.0,28,18,30

In [3]:
df.isnull().sum()

District_Name                        0
UnitName                             0
FIRNo                                0
RI                                   0
Year                                 0
Month                                0
Offence_From_Date                    0
Offence_To_Date                      1
FIR_Reg_DateTime                     0
FIR_Date                             0
FIR Type                             2
FIR_Stage                            0
Complaint_Mode                   18430
CrimeGroup_Name                      0
CrimeHead_Name                       0
Latitude                             5
Longitude                            5
ActSection                          42
IOName                             150
KGID                               150
IOAssigned_Date                1694182
Internal_IO                          0
Place of Offence                     0
Distance from PS                   567
Beat_Name                           64
Village_Area_Name                  138
Male                                 0
Female                               0
Boy                                  0
Girl                                 0
Age 0                                0
VICTIM COUNT                         0
Accused Count                        0
Arrested Male                        0
Arrested Female                      0
Arrested Count\tNo.                  0
Accused_ChargeSheeted Count          0
Conviction Count                     0
FIR_ID                               0
Unit_ID                              0
Crime_No                             0
Day_Offence_From                     0
Hour_Offence_From                    0
Minute_Offence_From                  0
Day_Offence_To                       1
Hour_Offence_To                      1
Minute_Offence_To                    1
Day_FIR_Reg                          0
Hour_FIR_Reg                         0
Minute_FIR_Reg                       0
dtype: int64

In [4]:
df.dropna()

,District_Name,UnitName,FIRNo,RI,Year,Month,Offence_From_Date,Offence_To_Date,FIR_Reg_DateTime,FIR_Date,...,Crime_No,Day_Offence_From,Hour_Offence_From,Minute_Offence_From,Day_Offence_To,Hour_Offence_To,Minute_Offence_To,Day_FIR_Reg,Hour_FIR_Reg,Minute_FIR_Reg
74913,Belagavi City,Market PS,0120/2023,1,2023,7,2023-05-03 15:30:00,2023-05-03 17:30:00,2023-07-08 19:16:00,08/07/2023,...,10982029220230120,3,15,30,3.0,17.0,30.0,8,19,16
357564,Bengaluru City,Kempapura Agrahara PS,0134/2022,1,2022,8,2022-08-12 22:00:00,2022-08-13 00:45:00,2022-08-25 20:10:00,25/08/2022,...,10443142720220134,12,22,0,13.0,0.0,45.0,25,20,10
703613,Chickballapura,Chickballapura Rural PS,0028/2024,1,2024,2,2024-02-13 01:30:00,2024-02-13 02:00:00,2024-02-17 18:30:00,17/02/2024,...,10976083420240028,13,1,30,13.0,2.0,0.0,17,18,30
705006,Chickballapura,Chickballapura Town PS,0095/2023,1,2023,7,2023-07-29 16:00:00,2023-07-29 21:45:00,2023-07-31 18:00:00,31/07/2023,...,10976083320230095,29,16,0,29.0,21.0,45.0,31,18,0
1196732,Mandya,Maddur PS,0257/2023,1,2023,8,2023-08-02 20:00:00,2023-08-03 05:30:00,2023-08-03 12:25:00,03/08/2023,...,10458087720230257,2,20,0,3.0,5.0,30.0,3,12,25
1284261,Mysuru City,V V Puram Traffic PS,0190/2018,1,2018,10,2018-10-30 05:20:00,2018-10-30 05:21:00,2018-10-30 17:00:00,30/10/2018,...,10973201420180190,30,5,20,30.0,5.0,21.0,30,17,0
1284319,Mysuru City,V V Puram Traffic PS,0011/2019,1,2019,1,2019-01-19 19:15:00,2019-01-19 19:16:00,2019-01-19 20:30:00,19/01/2019,...,10973201420190011,19,19,15,19.0,19.0,16.0,19,20,30
1528957,Tumakuru,Sira PS,0180/2023,1,2023,6,2023-05-29 10:30:00,2023-05-29 14:00:00,2023-06-26 12:15:00,26/06/2023,...,10464164220230180,29,10,30,29.0,14.0,0.0,26,12,15
1537615,Tumakuru,Tumakuru Rural PS,0223/2023,1,2023,8,2023-08-20 23:30:00,2023-08-21 06:30:00,2023-08-23 17:51:00,23/08/2023,...,10464108920230223,20,23,30,21.0,6.0,30.0,23,17,51

In [5]:
df['CrimeGroup_Name'] = df['CrimeGroup_Name'].astype(str)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1694191 entries, 0 to 1694190
Data columns (total 50 columns):
 #   Column                       Dtype
---  ------                       -----
 0   District_Name                object
 1   UnitName                     object
 2   FIRNo                        object
 3   RI                           int64
 4   Year                         int64
 5   Month                        int64
 6   Offence_From_Date            object
 7   Offence_To_Date              object
 8   FIR_Reg_DateTime             object
 9   FIR_Date                     object
 10  FIR Type                     object
 11  FIR_Stage                    object
 12  Complaint_Mode               object
 13  CrimeGroup_Name              object
 14  CrimeHead_Name               object
 15  Latitude                     float64
 16  Longitude                    float64
 17  ActSection                   object
 18  IOName                       object
 19  KGID                         object
 20  IOAssigned_Date              object
 21  Internal_IO                  int64
 22  Place of Offence             object
 23  Distance from PS             object
 24  Beat_Name                    object
 25  Village_Area_Name            object
 26  Male                         int64
 27  Female                       int64
 28  Boy                          int64
 29  Girl                         int64
 30  Age 0                        int64
 31  VICTIM COUNT                 int64
 32  Accused Count                int64
 33  Arrested Male                int64
 34  Arrested Female              int64
 35  Arrested Count	No.           int64
 36  Accused_ChargeSheeted Count  int64
 37  Conviction Count             int64
 38  FIR_ID                       int64
 39  Unit_ID                      int64
 40  Crime_No                     int64
 41  Day_Offence_From             int64
 42  Hour_Offence_From            int64
 43  Minute_Offence_From          int64
 44  Day_Offence_To               float64
 45  Hour_Offence_To              float64
 46  Minute_Offence_To            float64
 47  Day_FIR_Reg                  int64
 48  Hour_FIR_Reg                 int64
 49  Minute_FIR_Reg               int64
dtypes: float64(5), int64(25), object(20)
memory usage: 646.3+ MB

In [7]:
string_columns = df.select_dtypes(include=['object']).columns.tolist()
string_columns

['District_Name',
 'UnitName',
 'FIRNo',
 'Offence_From_Date',
 'Offence_To_Date',
 'FIR_Reg_DateTime',
 'FIR_Date',
 'FIR Type',
 'FIR_Stage',
 'Complaint_Mode',
 'CrimeGroup_Name',
 'CrimeHead_Name',
 'ActSection',
 'IOName',
 'KGID',
 'IOAssigned_Date',
 'Place of Offence',
 'Distance from PS',
 'Beat_Name',
 'Village_Area_Name']

In [8]:
enc = LabelEncoder()

for i in string_columns:
    df[i] = df[i].astype(str)
    df[i] = enc.fit_transform(df[i])
df.head()

,District_Name,UnitName,FIRNo,RI,Year,Month,Offence_From_Date,Offence_To_Date,FIR_Reg_DateTime,FIR_Date,...,Crime_No,Day_Offence_From,Hour_Offence_From,Minute_Offence_From,Day_Offence_To,Hour_Offence_To,Minute_Offence_To,Day_FIR_Reg,Hour_FIR_Reg,Minute_FIR_Reg
0,0,26,0,1,2016,1,19614,9263,555,396,...,10470124520160001,27,12,0,27.0,12.0,5.0,5,11,0
1,0,26,9,1,2016,1,21598,12320,1517,1088,...,10470124520160002,12,17,30,12.0,17.0,35.0,12,19,0
2,0,26,18,1,2016,1,21600,12324,1520,1088,...,10470124520160003,12,17,45,12.0,17.0,50.0,12,19,30
3,0,26,27,1,2016,1,21887,12829,1874,1382,...,10470124520160004,14,21,30,14.0,21.0,35.0,15,14,0
4,0,26,36,1,2016,1,22374,13649,2303,1676,...,10470124520160005,18,15,0,18.0,15.0,5.0,18,19,30

In [9]:
float_columns = df.select_dtypes(include=['float64']).columns.tolist()
float_columns

['Latitude',
 'Longitude',
 'Day_Offence_To',
 'Hour_Offence_To',
 'Minute_Offence_To']

In [10]:
enc = LabelEncoder()

for i in string_columns:
    df[i] = df[i].astype(float)
    df[i] = enc.fit_transform(df[i])
df.head()

,District_Name,UnitName,FIRNo,RI,Year,Month,Offence_From_Date,Offence_To_Date,FIR_Reg_DateTime,FIR_Date,...,Crime_No,Day_Offence_From,Hour_Offence_From,Minute_Offence_From,Day_Offence_To,Hour_Offence_To,Minute_Offence_To,Day_FIR_Reg,Hour_FIR_Reg,Minute_FIR_Reg
0,0,26,0,1,2016,1,19614,9263,555,396,...,10470124520160001,27,12,0,27.0,12.0,5.0,5,11,0
1,0,26,9,1,2016,1,21598,12320,1517,1088,...,10470124520160002,12,17,30,12.0,17.0,35.0,12,19,0
2,0,26,18,1,2016,1,21600,12324,1520,1088,...,10470124520160003,12,17,45,12.0,17.0,50.0,12,19,30
3,0,26,27,1,2016,1,21887,12829,1874,1382,...,10470124520160004,14,21,30,14.0,21.0,35.0,15,14,0
4,0,26,36,1,2016,1,22374,13649,2303,1676,...,10470124520160005,18,15,0,18.0,15.0,5.0,18,19,30

In [11]:
df.corr()

,District_Name,UnitName,FIRNo,RI,Year,Month,Offence_From_Date,Offence_To_Date,FIR_Reg_DateTime,FIR_Date,...,Crime_No,Day_Offence_From,Hour_Offence_From,Minute_Offence_From,Day_Offence_To,Hour_Offence_To,Minute_Offence_To,Day_FIR_Reg,Hour_FIR_Reg,Minute_FIR_Reg
District_Name,1.000000,0.133658,-0.191262,NaN,-0.023647,-0.020864,-0.016787,-0.025517,-0.025482,-0.005221,...,0.046801,-0.000690,0.044863,0.024009,-0.001885,0.021487,0.018726,-0.004455,0.032744,-0.016003
UnitName,0.133658,1.000000,-0.018154,NaN,0.006246,-0.000037,0.005978,0.005347,0.005501,-0.000501,...,-0.006954,-0.001063,-0.006021,0.000438,0.000094,0.008306,0.010404,-0.000518,-0.012489,-0.000997
FIRNo,-0.191262,-0.018154,1.000000,NaN,-0.050674,0.395494,0.002093,-0.000852,-0.000468,0.045651,...,0.007931,0.016905,-0.147667,-0.058937,0.019850,-0.063071,-0.000385,0.033177,-0.069034,0.008434
RI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Year,-0.023647,0.006246,-0.050674,NaN,1.000000,-0.022509,0.954757,0.984086,0.992084,0.001447,...,0.000963,0.008691,0.047090,0.012561,0.002729,0.064890,0.025516,-0.000681,0.055914,-0.005632
Month,-0.020864,-0.000037,0.395494,NaN,-0.022509,1.000000,0.090418,0.093079,0.097180,0.048759,...,0.014532,0.014096,0.014305,0.006511,0.013202,0.004497,0.003781,0.016890,0.004258,-0.004780
Offence_From_Date,-0.016787,0.005978,0.002093,NaN,0.954757,0.090418,1.000000,0.972425,0.961610,0.015913,...,0.002695,0.036102,0.112648,0.051919,0.009407,0.096533,0.060488,0.010303,0.050239,-0.002393
Offence_To_Date,-0.025517,0.005347,-0.000852,NaN,0.984086,0.093079,0.972425,1.000000,0.991201,0.016042,...,0.002575,0.018853,0.060847,0.022466,0.010224,0.071793,0.034165,0.010269,0.055089,-0.004583
FIR_Reg_DateTime,-0.025482,0.005501,-0.000468,NaN,0.992084,0.097180,0.961610,0.991201,1.000000,0.016794,...,0.003018,0.016269,0.048370,0.013256,0.011020,0.064727,0.025792,0.010877,0.056162,-0.006342
FIR_Date,-0.005221,-0.000501,0.045651,NaN,0.001447,0.048759,0.015913,0.016042,0.016794,1.000000,...,0.000926,0.635001,0.008513,0.003391,0.715732,0.005696,0.001431,0.999463,0.006513,-0.001157
FIR Type,-0.030747,0.003021,0.016817,NaN,-0.008292,-0.011657,-0.007118,-0.011523,-0.010520,-0.002780,...,0.000720,-0.000812,-0.018166,-0.014453,-0.003524,0.001142,-0.007900,-0.002381,0.039970,0.018491
FIR_Stage,-0.134755,0.001700,0.207661,NaN,0.219038,0.018079,0.208577,0.214234,0.219900,0.002614,...,0.012145,0.002849,-0.034028,-0.066028,0.001649,-0.073784,-0.058059,0.001461,-0.036595,-0.021279
Complaint_Mode,-0.091431,0.010850,0.083319,NaN,0.028421,0.005766,0.063293,0.049252,0.028876,-0.001378,...,0.003352,0.006524,0.004976,0.005108,-0.001541,-0.007541,0.006107,-0.001704,-0.015522,-0.018070
CrimeGroup_Name,0.028612,-0.006353,-0.217974,NaN,0.011632,0.019886,0.057195,0.023572,0.013245,0.009598,...,-0.014313,0.029371,0.190099,0.116052,0.006303,0.025718,0.054979,0.008893,0.028411,0.010073
CrimeHead_Name,0.080238,-0.010511,-0.100464,NaN,-0.107212,-0.047147,-0.055066,-0.095170,-0.112867,-0.010388,...,-0.007940,0.004841,0.079166,0.055520,-0.010856,0.065454,0.049094,-0.008567,-0.026965,0.001100
Latitude,-0.094321,0.013262,-0.067211,NaN,0.228767,-0.021688,0.217375,0.223313,0.226677,-0.002095,...,-0.010033,0.001477,0.036855,0.016012,-0.001001,0.009813,0.001145,-0.002064,0.025203,0.013198
Longitude,-0.053810,0.012062,-0.094081,NaN,0.404330,-0.021809,0.387899,0.398310,0.403213,-0.005404,...,-0.005997,0.001893,0.056500,0.028822,-0.002764,0.029740,0.011817,-0.005858,0.041268,0.005864
ActSection,0.000801,-0.019869,0.032032,NaN,0.118261,0.053027,0.104644,0.118910,0.125198,0.016342,...,0.006757,0.017763,0.077760,0.022052,0.016715,0.003540,0.007836,0.014287,0.094460,0.041355
IOName,0.008254,0.019286,-0.085822,NaN,0.010721,-0.000092,0.008442,0.009784,0.009899,0.000737,...,-0.009616,0.000115,0.016230,0.002650,0.000296,0.015633,0.005640,0.000708,0.003004,-0.000378
KGID,-0.119390,0.011502,0.005384,NaN,-0.067549,-0.004094,-0.073595,-0.070505,-0.069637,-0.000042,...,-0.013129,-0.003217,-0.009100,-0.010714,0.000059,-0.016624,-0.014091,0.000268,-0.003092,0.008326
IOAssigned_Date,-0.000557,-0.001177,0.000179,NaN,-0.001946,-0.000106,-0.002022,-0.001962,-0.001958,-0.000232,...,-0.000561,0.000311,-0.000398,-0.000248,0.000304,0.001500,-0.000481,-0.000228,-0.000939,-0.000366
Internal_IO,-0.069284,0.011440,0.074263,NaN,-0.000755,0.010365,-0.002574,0.000808,0.000680,0.000433,...,-0.014871,0.000140,-0.012868,-0.002394,0.000369,-0.006963,0.000199,0.000106,-0.014723,0.007139
Place of Offence,-0.065068,0.078779,0.119744,NaN,0.021884,0.011506,0.017667,0.022100,0.023273,0.001524,...,0.004817,-0.000014,-0.044391,-0.005097,0.001227,0.001908,0.015157,0.001085,-0.029886,-0.001485
Distance from PS,-0.092211,0.006156,0.080348,NaN,0.078082,0.011532,0.072715,0.078069,0.078616,0.002617,...,-0.008674,-0.001585,-0.016198,-0.003292,0.000040,-0.005218,-0.005622,0.002012,0.002904,0.006233
Beat_Name,-0.041427,-0.015901,0.068245,NaN,0.028663,0.001999,0.028167,0.028882,0.028528,0.001669,...,-0.013981,0.003621,-0.024632,0.004951,0.002104,0.019600,0.022009,0.001523,-0.023215,-0.027055
Village_Area_Name,-0.002372,0.130107,-0.047190,NaN,0.023447,0.000890,0.019849,0.022294,0.022665,0.000387,...,-0.001481,0.000312,-0.002100,0.008790,0.000315,0.012411,0.009843,0.000288,-0.007013,-0.005924
Male,0.036257,0.007592,-0.064235,NaN,0.148595,0.016252,0.158700,0.150775,0.152363,0.004249,...,-0.003892,0.013799,0.099159,0.059214,0.003496,0.072219,0.051633,0.003292,-0.004734,-0.020093
Female,0.014783,-0.000498,-0.029198,NaN,0.098734,0.013157,0.082370,0.099864,0.100842,0.002819,...,-0.002727,0.001230,-0.029374,-0.031328,0.002278,0.007055,-0.026167,0.002103,0.030306,-0.020374
Boy,0.011140,0.000272,-0.018228,NaN,0.011975,0.004385,0.018338,0.014101,0.012659,0.000939,...,-0.000521,0.004982,0.010222,0.013751,0.001597,0.013079,0.009176,0.000763,0.007135,-0.006361
Girl,0.011666,-0.000599,-0.022446,NaN,0.037102,0.006715,0.040237,0.038274,0.037882,0.002814,...,-0.001493,-0.002655,-0.021620,-0.019876,0.002499,-0.004792,-0.024957,0.002486,0.019848,-0.007957
Age 0,0.034664,-0.001217,0.001401,NaN,-0.115340,-0.002454,-0.109669,-0.115684,-0.118376,-0.001247,...,-0.001704,0.003054,0.017927,0.014716,-0.000239,0.016118,0.014067,-0.000847,-0.003514,-0.004003
VICTIM COUNT,-0.002436,0.000716,-0.001063,NaN,0.001215,0.000599,0.001323,0.001271,0.001277,0.000274,...,0.000055,-0.000299,0.002426,0.001083,-0.000118,0.001811,0.001670,0.000246,0.000187,-0.000150
Accused Count,0.075759,-0.007032,-0.070931,NaN,-0.026402,-0.000852,-0.050132,-0.032503,-0.026412,0.000194,...,-0.002721,-0.004164,0.006311,-0.012090,0.001793,0.032096,-0.010858,0.000298,0.053387,0.007263
Arrested Male,0.040951,-0.014406,-0.077284,NaN,-0.048350,0.005213,-0.038305,-0.042750,-0.046761,0.002433,...,0.001414,0.009664,0.075146,0.054038,0.002866,0.063513,0.047981,0.002364,0.027474,0.020047
Arrested Female,0.017828,-0.015005,-0.032763,NaN,0.004210,0.003899,-0.018828,0.002774,0.004869,0.001027,...,-0.000018,-0.002161,-0.027660,-0.034747,0.001386,-0.007511,-0.027966,0.000878,0.026269,-0.007209
Arrested Count\tNo.,0.041858,-0.016727,-0.078859,NaN,-0.043548,0.005716,-0.039581,-0.038711,-0.041930,0.002518,...,0.001310,0.008460,0.062985,0.041888,0.003004,0.056881,0.037872,0.002419,0.031368,0.016840
Accused_ChargeSheeted Count,0.065813,-0.007076,-0.055354,NaN,-0.032276,0.012572,-0.022651,-0.026020,-0.030322,0.001902,...,-0.002994,0.009200,0.074301,0.036624,0.001765,0.066207,0.033664,0.001547,0.042941,0.017579
Conviction Count,0.043650,-0.011510,-0.056386,NaN,-0.024698,0.003897,-0.005854,-0.017641,-0.022195,0.002619,...,-0.002060,0.011768,0.073672,0.079475,0.002294,0.068633,0.067544,0.002520,0.040677,0.022132
FIR_ID,-0.023674,0.006237,-0.050494,NaN,1.000000,-0.022457,0.954764,0.984092,0.992090,0.001452,...,0.000995,0.008692,0.047064,0.012551,0.002731,0.064877,0.025516,-0.000678,0.055905,-0.005630
Unit_ID,-0.164605,0.011977,0.222597,NaN,0.071821,0.026059,0.070886,0.076497,0.075044,0.001964,...,-0.021285,-0.002312,-0.071349,-0.012062,-0.000907,-0.001160,0.007532,0.000917,-0.044148,-0.006175
Crime_No,0.046801,-0.006954,0.007931,NaN,0.000963,0.014532,0.002695,0.002575,0.003018,0.000926,...,1.000000,-0.001438,-0.012579,-0.001386,-0.001849,-0.009798,0.005107,0.000432,-0.004394,0.001010
Day_Offence_From,-0.000690,-0.001063,0.016905,NaN,0.008691,0.014096,0.036102,0.018853,0.016269,0.635001,...,-0.001438,1.000000,0.054363,0.029026,0.868857,0.026003,0.023027,0.635815,0.002978,0.000417
Hour_Offence_From,0.044863,-0.006021,-0.147667,NaN,0.047090,0.014305,0.112648,0.060847,0.048370,0.008513,...,-0.012579,0.054363,1.000000,0.168805,0.006632,0.642220,0.102384,0.007880,0.159593,0.019440
Minute_Offence_From,0.024009,0.000438,-0.058937,NaN,0.012561,0.006511,0.051919,0.022466,0.013256,0.003391,...,-0.001386,0.029026,0.168805,1.000000,0.002398,0.106527,0.545582,0.003121,0.007378,0.013066
Day_Offence_To,-0.001885,0.000094,0.019850,NaN,0.002729,0.013202,0.009407,0.010224,0.011020,0.715732,...,-0.001849,0.868857,0.006632,0.002398,1.000000,0.006360,0.000958,0.716641,0.005288,-0.001256
Hour_Offence_To,0.021487,0.008306,-0.063071,NaN,0.064890,0.004497,0.096533,0.071793,0.064727,0.005696,...,-0.009798,0.026003,0.642220,0.106527,0.006360,1.000000,0.136410,0.005335,0.213276,0.020012
Minute_Offence_To,0.018726,0.010404,-0.000385,NaN,0.025516,0.003781,0.060488,0.034165,0.025792,0.001431,...,0.005107,0.023027,0.102384,0.545582,0.000958,0.136410,1.000000,0.001209,-0.007141,0.030460
Day_FIR_Reg,-0.004455,-0.000518,0.033177,NaN,-0.000681,0.016890,0.010303,0.010269,0.010877,0.999463,...,0.000432,0.635815,0.007880,0.003121,0.716641,0.005335,0.001209,1.000000,0.006201,-0.000983
Hour_FIR_Reg,0.032744,-0.012489,-0.069034,NaN,0.055914,0.004258,0.050239,0.055089,0.056162,0.006513,...,-0.004394,0.002978,0.159593,0.007378,0.005288,0.213276,-0.007141,0.006201,1.000000,-0.016415
Minute_FIR_Reg,-0.016003,-0.000997,0.008434,NaN,-0.005632,-0.004780,-0.002393,-0.004583,-0.006342,-0.001157,...,0.001010,0.000417,0.019440,0.013066,-0.001256,0.020012,0.030460,-0.000983,-0.016415,1.000000

In [12]:
df = df.rename(columns={'Conviction Count': 'ConvictionCount'})

In [13]:
df.dropna()

,District_Name,UnitName,FIRNo,RI,Year,Month,Offence_From_Date,Offence_To_Date,FIR_Reg_DateTime,FIR_Date,...,Crime_No,Day_Offence_From,Hour_Offence_From,Minute_Offence_From,Day_Offence_To,Hour_Offence_To,Minute_Offence_To,Day_FIR_Reg,Hour_FIR_Reg,Minute_FIR_Reg
0,0,26,0,1,2016,1,19614,9263,555,396,...,10470124520160001,27,12,0,27.0,12.0,5.0,5,11,0
1,0,26,9,1,2016,1,21598,12320,1517,1088,...,10470124520160002,12,17,30,12.0,17.0,35.0,12,19,0
2,0,26,18,1,2016,1,21600,12324,1520,1088,...,10470124520160003,12,17,45,12.0,17.0,50.0,12,19,30
3,0,26,27,1,2016,1,21887,12829,1874,1382,...,10470124520160004,14,21,30,14.0,21.0,35.0,15,14,0
4,0,26,36,1,2016,1,22374,13649,2303,1676,...,10470124520160005,18,15,0,18.0,15.0,5.0,18,19,30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1694186,40,1038,17,1,2024,1,433115,701219,380384,998,...,10978218320240002,10,5,30,10.0,21.0,30.0,11,21,30
1694187,40,1038,26,1,2024,1,434559,703386,382620,2762,...,10978218320240003,19,22,30,19.0,22.0,35.0,29,19,30
1694188,40,1038,35,1,2024,2,437087,707596,383870,611,...,10978218320240004,6,15,42,6.0,15.0,45.0,7,17,45
1694189,40,1038,44,1,2024,2,438967,710756,386176,2281,...,10978218320240005,19,12,10,19.0,12.0,15.0,24,17,0
1694190,40,1038,53,1,2024,2,440081,712604,386731,2673,...,10978218320240006,26,22,30,26.0,22.0,45.0,28,18,30

In [20]:
Y = df.ConvictionCount
X = df.iloc[:,[4,5,6,12,13,14,22,31,32,35,36]] 
X.head()

,Year,Month,Offence_From_Date,Complaint_Mode,CrimeGroup_Name,CrimeHead_Name,Place of Offence,VICTIM COUNT,Accused Count,Arrested Count\tNo.,Accused_ChargeSheeted Count
0,2016,1,19614,8,86,351,537660,0,1,1,1
1,2016,1,21598,7,66,437,1113786,0,5,5,5
2,2016,1,21600,7,66,178,1113770,0,1,1,1
3,2016,1,21887,8,73,285,118514,0,1,1,1
4,2016,1,22374,8,72,350,44940,0,1,1,1

In [21]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.3,random_state=10)

In [22]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
from sklearn.svm import SVC
rbf_svc = SVC(kernel='rbf', C=100, random_state=10).fit(X_train,Y_train)

In [ ]:
Y_predict_svm = rbf_svc.predict(X_test)

In [ ]:
from sklearn.naive_bayes import BernoulliNB
model_nb = BernoulliNB()
model_nb.fit(X_train,Y_train)

In [ ]:
Y_predict_nb = model_nb.predict(X_test)

In [ ]:
from sklearn.neural_network import MLPClassifier
model_mlp = MLPClassifier(hidden_layer_sizes=(100,100,100),batch_size=10,learning_rate_init=0.01,max_iter=2000,random_state=10)
model_mlp.fit(X_train,Y_train)

In [ ]:
Y_predict_mlp = model_mlp.predict(X_test)