In [68]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import tree
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import mean_squared_error
from sklearn.tree import DecisionTreeClassifier

In [69]:
df = pd.read_csv("C:\\Users\\hp\\Downloads\\FIR_Details_Data.csv")
df.head()

C:\Users\hp\AppData\Local\Temp\ipykernel_7392\1830483871.py:1: DtypeWarning: Columns (19,20) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("C:\\Users\\hp\\Downloads\\FIR_Details_Data.csv")

,District_Name,UnitName,FIRNo,RI,Year,Month,Offence_From_Date,Offence_To_Date,FIR_Reg_DateTime,FIR_Date,...,VICTIM COUNT,Accused Count,Arrested Male,Arrested Female,Arrested Count\tNo.,Accused_ChargeSheeted Count,Conviction Count,FIR_ID,Unit_ID,Crime_No
0,Bagalkot,Amengad PS,0001/2016,1,2016,1,2015-12-27 12:00:00.000,2015-12-27 12:05:00.000,2016-01-05 11:00:00.000,05/01/2016,...,0,1,1,0,1,1,0,2016000002,1245,10470124520160001
1,Bagalkot,Amengad PS,0002/2016,1,2016,1,2016-01-12 17:30:00.000,2016-01-12 17:35:00.000,2016-01-12 19:00:00.000,12/01/2016,...,0,5,5,0,5,5,2,2016000003,1245,10470124520160002
2,Bagalkot,Amengad PS,0003/2016,1,2016,1,2016-01-12 17:45:00.000,2016-01-12 17:50:00.000,2016-01-12 19:30:00.000,12/01/2016,...,0,1,1,0,1,1,0,2016000004,1245,10470124520160003
3,Bagalkot,Amengad PS,0004/2016,1,2016,1,2016-01-14 21:30:00.000,2016-01-14 21:35:00.000,2016-01-15 14:00:00.000,15/01/2016,...,0,1,1,0,1,1,0,2016000005,1245,10470124520160004
4,Bagalkot,Amengad PS,0005/2016,1,2016,1,2016-01-18 15:00:00.000,2016-01-18 15:05:00.000,2016-01-18 19:30:00.000,18/01/2016,...,0,1,1,0,1,1,0,2016000006,1245,10470124520160005

In [70]:
df.shape

(1694191, 41)

In [71]:
df.columns

Index(['District_Name', 'UnitName', 'FIRNo', 'RI', 'Year', 'Month',
       'Offence_From_Date', 'Offence_To_Date', 'FIR_Reg_DateTime', 'FIR_Date',
       'FIR Type', 'FIR_Stage', 'Complaint_Mode', 'CrimeGroup_Name',
       'CrimeHead_Name', 'Latitude', 'Longitude', 'ActSection', 'IOName',
       'KGID', 'IOAssigned_Date', 'Internal_IO', 'Place of Offence',
       'Distance from PS', 'Beat_Name', 'Village_Area_Name', 'Male', 'Female',
       'Boy', 'Girl', 'Age 0', 'VICTIM COUNT', 'Accused Count',
       'Arrested Male', 'Arrested Female', 'Arrested Count\tNo.',
       'Accused_ChargeSheeted Count', 'Conviction Count', 'FIR_ID', 'Unit_ID',
       'Crime_No'],
      dtype='object')

In [72]:
df.info

<bound method DataFrame.info of         District_Name          UnitName      FIRNo  RI  Year  Month  \
0            Bagalkot        Amengad PS  0001/2016   1  2016      1
1            Bagalkot        Amengad PS  0002/2016   1  2016      1
2            Bagalkot        Amengad PS  0003/2016   1  2016      1
3            Bagalkot        Amengad PS  0004/2016   1  2016      1
4            Bagalkot        Amengad PS  0005/2016   1  2016      1
...               ...               ...        ...  ..   ...    ...
1694186        Yadgir  Yadgiri Women PS  0002/2024   1  2024      1
1694187        Yadgir  Yadgiri Women PS  0003/2024   1  2024      1
1694188        Yadgir  Yadgiri Women PS  0004/2024   1  2024      2
1694189        Yadgir  Yadgiri Women PS  0005/2024   1  2024      2
1694190        Yadgir  Yadgiri Women PS  0006/2024   1  2024      2

               Offence_From_Date          Offence_To_Date  \
0        2015-12-27 12:00:00.000  2015-12-27 12:05:00.000
1        2016-01-12 17:30:00.000  2016-01-12 17:35:00.000
2        2016-01-12 17:45:00.000  2016-01-12 17:50:00.000
3        2016-01-14 21:30:00.000  2016-01-14 21:35:00.000
4        2016-01-18 15:00:00.000  2016-01-18 15:05:00.000
...                          ...                      ...
1694186  2024-01-10 05:30:00.000  2024-01-10 21:30:00.000
1694187  2024-01-19 22:30:00.000  2024-01-19 22:35:00.000
1694188  2024-02-06 15:42:00.000  2024-02-06 15:45:00.000
1694189  2024-02-19 12:10:00.000  2024-02-19 12:15:00.000
1694190  2024-02-26 22:30:00.000  2024-02-26 22:45:00.000

                FIR_Reg_DateTime    FIR_Date  ... VICTIM COUNT Accused Count  \
0        2016-01-05 11:00:00.000  05/01/2016  ...            0             1
1        2016-01-12 19:00:00.000  12/01/2016  ...            0             5
2        2016-01-12 19:30:00.000  12/01/2016  ...            0             1
3        2016-01-15 14:00:00.000  15/01/2016  ...            0             1
4        2016-01-18 19:30:00.000  18/01/2016  ...            0             1
...                          ...         ...  ...          ...           ...
1694186  2024-01-11 21:30:00.000  11/01/2024  ...            0             0
1694187  2024-01-29 19:30:00.000  29/01/2024  ...            0             1
1694188  2024-02-07 17:45:00.000  07/02/2024  ...            0             1
1694189  2024-02-24 17:00:00.000  24/02/2024  ...            0             5
1694190  2024-02-28 18:30:00.000  28/02/2024  ...            0             1

        Arrested Male Arrested Female Arrested Count\tNo.  \
0                   1               0                   1
1                   5               0                   5
2                   1               0                   1
3                   1               0                   1
4                   1               0                   1
...               ...             ...                 ...
1694186             0               0                   0
1694187             0               0                   0
1694188             0               0                   0
1694189             0               0                   0
1694190             0               0                   0

         Accused_ChargeSheeted Count  Conviction Count      FIR_ID Unit_ID  \
0                                  1                 0  2016000002    1245
1                                  5                 2  2016000003    1245
2                                  1                 0  2016000004    1245
3                                  1                 0  2016000005    1245
4                                  1                 0  2016000006    1245
...                              ...               ...         ...     ...
1694186                            0                 0  2024000002    2183
1694187                            0                 0  2024000003    2183
1694188                            0                 0  2024000004    2183
1694189                            0                 0  2024000005    2183
1694190                            0                 0  2024000006    2183

                  Crime_No
0        10470124520160001
1        10470124520160002
2        10470124520160003
3        10470124520160004
4        10470124520160005
...                    ...
1694186  10978218320240002
1694187  10978218320240003
1694188  10978218320240004
1694189  10978218320240005
1694190  10978218320240006

[1694191 rows x 41 columns]>

In [73]:
df.isnull().sum()

District_Name                        0
UnitName                             0
FIRNo                                0
RI                                   0
Year                                 0
Month                                0
Offence_From_Date                    0
Offence_To_Date                      1
FIR_Reg_DateTime                     0
FIR_Date                             0
FIR Type                             2
FIR_Stage                            0
Complaint_Mode                   18430
CrimeGroup_Name                      0
CrimeHead_Name                       0
Latitude                             5
Longitude                            5
ActSection                          42
IOName                             150
KGID                               150
IOAssigned_Date                1694182
Internal_IO                          0
Place of Offence                     0
Distance from PS                   567
Beat_Name                           64
Village_Area_Name                  138
Male                                 0
Female                               0
Boy                                  0
Girl                                 0
Age 0                                0
VICTIM COUNT                         0
Accused Count                        0
Arrested Male                        0
Arrested Female                      0
Arrested Count\tNo.                  0
Accused_ChargeSheeted Count          0
Conviction Count                     0
FIR_ID                               0
Unit_ID                              0
Crime_No                             0
dtype: int64

In [74]:
df.dropna()

,District_Name,UnitName,FIRNo,RI,Year,Month,Offence_From_Date,Offence_To_Date,FIR_Reg_DateTime,FIR_Date,...,VICTIM COUNT,Accused Count,Arrested Male,Arrested Female,Arrested Count\tNo.,Accused_ChargeSheeted Count,Conviction Count,FIR_ID,Unit_ID,Crime_No
74913,Belagavi City,Market PS,0120/2023,1,2023,7,2023-05-03 15:30:00.000,2023-05-03 17:30:00.000,2023-07-08 19:16:00.000,08/07/2023,...,0,0,0,0,0,0,0,2023000205,292,10982029220230120
357564,Bengaluru City,Kempapura Agrahara PS,0134/2022,1,2022,8,2022-08-12 22:00:00.000,2022-08-13 00:45:00.000,2022-08-25 20:10:00.000,25/08/2022,...,0,1,0,0,0,1,0,2022000206,1427,10443142720220134
703613,Chickballapura,Chickballapura Rural PS,0028/2024,1,2024,2,2024-02-13 01:30:00.000,2024-02-13 02:00:00.000,2024-02-17 18:30:00.000,17/02/2024,...,0,1,0,0,0,0,0,2024000054,834,10976083420240028
705006,Chickballapura,Chickballapura Town PS,0095/2023,1,2023,7,2023-07-29 16:00:00.000,2023-07-29 21:45:00.000,2023-07-31 18:00:00.000,31/07/2023,...,0,0,0,0,0,0,0,2023000131,833,10976083320230095
1196732,Mandya,Maddur PS,0257/2023,1,2023,8,2023-08-02 20:00:00.000,2023-08-03 05:30:00.000,2023-08-03 12:25:00.000,03/08/2023,...,0,0,0,0,0,0,0,2023000348,877,10458087720230257
1284261,Mysuru City,V V Puram Traffic PS,0190/2018,1,2018,10,2018-10-30 05:20:00.000,2018-10-30 05:21:00.000,2018-10-30 17:00:00.000,30/10/2018,...,0,1,0,0,0,1,0,2018000190,2014,10973201420180190
1284319,Mysuru City,V V Puram Traffic PS,0011/2019,1,2019,1,2019-01-19 19:15:00.000,2019-01-19 19:16:00.000,2019-01-19 20:30:00.000,19/01/2019,...,0,1,0,0,0,1,0,2019000011,2014,10973201420190011
1528957,Tumakuru,Sira PS,0180/2023,1,2023,6,2023-05-29 10:30:00.000,2023-05-29 14:00:00.000,2023-06-26 12:15:00.000,26/06/2023,...,0,0,0,0,0,0,0,2023000217,1642,10464164220230180
1537615,Tumakuru,Tumakuru Rural PS,0223/2023,1,2023,8,2023-08-20 23:30:00.000,2023-08-21 06:30:00.000,2023-08-23 17:51:00.000,23/08/2023,...,0,1,0,0,0,0,0,2023000356,1089,10464108920230223

In [76]:
df['CrimeGroup_Name'] = df['CrimeGroup_Name'].astype(str)

In [77]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1694191 entries, 0 to 1694190
Data columns (total 41 columns):
 #   Column                       Dtype
---  ------                       -----
 0   District_Name                object
 1   UnitName                     object
 2   FIRNo                        object
 3   RI                           int64
 4   Year                         int64
 5   Month                        int64
 6   Offence_From_Date            object
 7   Offence_To_Date              object
 8   FIR_Reg_DateTime             object
 9   FIR_Date                     object
 10  FIR Type                     object
 11  FIR_Stage                    object
 12  Complaint_Mode               object
 13  CrimeGroup_Name              object
 14  CrimeHead_Name               object
 15  Latitude                     float64
 16  Longitude                    float64
 17  ActSection                   object
 18  IOName                       object
 19  KGID                         object
 20  IOAssigned_Date              object
 21  Internal_IO                  int64
 22  Place of Offence             object
 23  Distance from PS             object
 24  Beat_Name                    object
 25  Village_Area_Name            object
 26  Male                         int64
 27  Female                       int64
 28  Boy                          int64
 29  Girl                         int64
 30  Age 0                        int64
 31  VICTIM COUNT                 int64
 32  Accused Count                int64
 33  Arrested Male                int64
 34  Arrested Female              int64
 35  Arrested Count	No.           int64
 36  Accused_ChargeSheeted Count  int64
 37  Conviction Count             int64
 38  FIR_ID                       int64
 39  Unit_ID                      int64
 40  Crime_No                     int64
dtypes: float64(2), int64(19), object(20)
memory usage: 530.0+ MB

In [78]:
string_columns = df.select_dtypes(include=['object']).columns.tolist()
string_columns

['District_Name',
 'UnitName',
 'FIRNo',
 'Offence_From_Date',
 'Offence_To_Date',
 'FIR_Reg_DateTime',
 'FIR_Date',
 'FIR Type',
 'FIR_Stage',
 'Complaint_Mode',
 'CrimeGroup_Name',
 'CrimeHead_Name',
 'ActSection',
 'IOName',
 'KGID',
 'IOAssigned_Date',
 'Place of Offence',
 'Distance from PS',
 'Beat_Name',
 'Village_Area_Name']

In [79]:
enc = LabelEncoder()

for i in string_columns:
    df[i] = df[i].astype(str)
    df[i] = enc.fit_transform(df[i])
df.head()

,District_Name,UnitName,FIRNo,RI,Year,Month,Offence_From_Date,Offence_To_Date,FIR_Reg_DateTime,FIR_Date,...,VICTIM COUNT,Accused Count,Arrested Male,Arrested Female,Arrested Count\tNo.,Accused_ChargeSheeted Count,Conviction Count,FIR_ID,Unit_ID,Crime_No
0,0,26,0,1,2016,1,19614,9263,491,396,...,0,1,1,0,1,1,0,2016000002,1245,10470124520160001
1,0,26,9,1,2016,1,21598,12320,1338,1088,...,0,5,5,0,5,5,2,2016000003,1245,10470124520160002
2,0,26,18,1,2016,1,21600,12324,1341,1088,...,0,1,1,0,1,1,0,2016000004,1245,10470124520160003
3,0,26,27,1,2016,1,21887,12829,1652,1382,...,0,1,1,0,1,1,0,2016000005,1245,10470124520160004
4,0,26,36,1,2016,1,22374,13649,2025,1676,...,0,1,1,0,1,1,0,2016000006,1245,10470124520160005

In [80]:
df.corr()

,District_Name,UnitName,FIRNo,RI,Year,Month,Offence_From_Date,Offence_To_Date,FIR_Reg_DateTime,FIR_Date,...,VICTIM COUNT,Accused Count,Arrested Male,Arrested Female,Arrested Count\tNo.,Accused_ChargeSheeted Count,Conviction Count,FIR_ID,Unit_ID,Crime_No
District_Name,1.000000,0.133658,-0.191262,NaN,-0.023647,-0.020864,-0.016787,-0.025517,-0.025601,-0.005221,...,-0.002436,0.075759,0.040951,0.017828,0.041858,0.065813,0.043650,-0.023674,-0.164605,0.046801
UnitName,0.133658,1.000000,-0.018154,NaN,0.006246,-0.000037,0.005978,0.005347,0.005630,-0.000501,...,0.000716,-0.007032,-0.014406,-0.015005,-0.016727,-0.007076,-0.011510,0.006237,0.011977,-0.006954
FIRNo,-0.191262,-0.018154,1.000000,NaN,-0.050674,0.395494,0.002093,-0.000852,-0.001155,0.045651,...,-0.001063,-0.070931,-0.077284,-0.032763,-0.078859,-0.055354,-0.056386,-0.050494,0.222597,0.007931
RI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Year,-0.023647,0.006246,-0.050674,NaN,1.000000,-0.022509,0.954757,0.984086,0.992398,0.001447,...,0.001215,-0.026402,-0.048350,0.004210,-0.043548,-0.032276,-0.024698,1.000000,0.071821,0.000963
Month,-0.020864,-0.000037,0.395494,NaN,-0.022509,1.000000,0.090418,0.093079,0.096519,0.048759,...,0.000599,-0.000852,0.005213,0.003899,0.005716,0.012572,0.003897,-0.022457,0.026059,0.014532
Offence_From_Date,-0.016787,0.005978,0.002093,NaN,0.954757,0.090418,1.000000,0.972425,0.961674,0.015913,...,0.001323,-0.050132,-0.038305,-0.018828,-0.039581,-0.022651,-0.005854,0.954764,0.070886,0.002695
Offence_To_Date,-0.025517,0.005347,-0.000852,NaN,0.984086,0.093079,0.972425,1.000000,0.991247,0.016042,...,0.001271,-0.032503,-0.042750,0.002774,-0.038711,-0.026020,-0.017641,0.984092,0.076497,0.002575
FIR_Reg_DateTime,-0.025601,0.005630,-0.001155,NaN,0.992398,0.096519,0.961674,0.991247,1.000000,0.016773,...,0.001277,-0.026408,-0.046945,0.004803,-0.042115,-0.030439,-0.022600,0.992404,0.074942,0.002973
FIR_Date,-0.005221,-0.000501,0.045651,NaN,0.001447,0.048759,0.015913,0.016042,0.016773,1.000000,...,0.000274,0.000194,0.002433,0.001027,0.002518,0.001902,0.002619,0.001452,0.001964,0.000926
FIR Type,-0.030747,0.003021,0.016817,NaN,-0.008292,-0.011657,-0.007118,-0.011523,-0.010351,-0.002780,...,-0.000670,0.020767,-0.029080,-0.031085,-0.034033,-0.014125,0.094127,-0.008289,0.004719,0.000720
FIR_Stage,-0.134755,0.001700,0.207661,NaN,0.219038,0.018079,0.208577,0.214234,0.220270,0.002614,...,-0.000739,-0.177249,-0.192430,-0.065169,-0.192592,-0.251481,-0.142137,0.219073,0.119910,0.012145
Complaint_Mode,-0.091431,0.010850,0.083319,NaN,0.028421,0.005766,0.063293,0.049252,0.028899,-0.001378,...,0.001266,-0.096077,-0.022222,-0.024491,-0.026104,-0.037032,-0.018227,0.028433,0.088211,0.003352
CrimeGroup_Name,0.028612,-0.006353,-0.217974,NaN,0.011632,0.019886,0.057195,0.023572,0.013360,0.009598,...,-0.001063,-0.054909,0.039889,-0.042281,0.027086,0.014081,0.098019,0.011595,-0.084016,-0.014313
CrimeHead_Name,0.080238,-0.010511,-0.100464,NaN,-0.107212,-0.047147,-0.055066,-0.095170,-0.112776,-0.010388,...,-0.000031,0.027847,0.028567,-0.052105,0.014356,0.043340,0.102649,-0.107230,-0.060634,-0.007940
Latitude,-0.094321,0.013262,-0.067211,NaN,0.228767,-0.021688,0.217375,0.223313,0.226715,-0.002095,...,0.000536,-0.012576,0.001429,-0.000354,0.001247,-0.012639,-0.019447,0.228759,0.007774,-0.010033
Longitude,-0.053810,0.012062,-0.094081,NaN,0.404330,-0.021809,0.387899,0.398310,0.403056,-0.005404,...,0.001388,-0.012908,0.002371,-0.000748,0.002044,-0.015373,-0.009014,0.404319,0.023559,-0.005997
ActSection,0.000801,-0.019869,0.032032,NaN,0.118261,0.053027,0.104644,0.118910,0.124999,0.016342,...,-0.000954,0.082932,0.161214,0.019952,0.153328,0.148857,0.174790,0.118274,-0.028592,0.006757
IOName,0.008254,0.019286,-0.085822,NaN,0.010721,-0.000092,0.008442,0.009784,0.010028,0.000737,...,0.000023,-0.000730,-0.000099,0.002601,0.000492,-0.003035,-0.003098,0.010703,-0.010953,-0.009616
KGID,-0.119390,0.011502,0.005384,NaN,-0.067549,-0.004094,-0.073595,-0.070505,-0.069255,-0.000042,...,0.001951,-0.015053,-0.015344,-0.004643,-0.015192,-0.021781,-0.044386,-0.067551,0.043533,-0.013129
IOAssigned_Date,-0.000557,-0.001177,0.000179,NaN,-0.001946,-0.000106,-0.002022,-0.001962,-0.001958,-0.000232,...,0.000022,0.000913,0.000962,0.000367,0.000972,0.000964,0.000612,-0.001946,0.000126,-0.000561
Internal_IO,-0.069284,0.011440,0.074263,NaN,-0.000755,0.010365,-0.002574,0.000808,0.000646,0.000433,...,0.001097,-0.029344,-0.008748,-0.008889,-0.010086,-0.024810,-0.010949,-0.000743,0.203906,-0.014871
Place of Offence,-0.065068,0.078779,0.119744,NaN,0.021884,0.011506,0.017667,0.022100,0.023242,0.001524,...,0.001019,-0.032980,-0.017204,-0.024407,-0.021479,-0.027358,-0.001022,0.021899,0.118217,0.004817
Distance from PS,-0.092211,0.006156,0.080348,NaN,0.078082,0.011532,0.072715,0.078069,0.078720,0.002617,...,0.000424,-0.018010,-0.005532,-0.001150,-0.005368,-0.013359,-0.007664,0.078096,0.079854,-0.008674
Beat_Name,-0.041427,-0.015901,0.068245,NaN,0.028663,0.001999,0.028167,0.028882,0.028562,0.001669,...,-0.000660,-0.018477,-0.013426,0.003862,-0.011562,-0.010289,0.018587,0.028672,0.092278,-0.013981
Village_Area_Name,-0.002372,0.130107,-0.047190,NaN,0.023447,0.000890,0.019849,0.022294,0.022809,0.000387,...,-0.001805,-0.013896,-0.007374,-0.003139,-0.007524,-0.015971,-0.002765,0.023433,0.020243,-0.001481
Male,0.036257,0.007592,-0.064235,NaN,0.148595,0.016252,0.158700,0.150775,0.151879,0.004249,...,-0.004919,0.048467,0.052396,0.020175,0.052975,0.062206,-0.055435,0.148584,-0.017115,-0.003892
Female,0.014783,-0.000498,-0.029198,NaN,0.098734,0.013157,0.082370,0.099864,0.100659,0.002819,...,-0.001767,0.050787,0.004489,0.154817,0.039709,0.028407,-0.077721,0.098729,0.004089,-0.002727
Boy,0.011140,0.000272,-0.018228,NaN,0.011975,0.004385,0.018338,0.014101,0.012618,0.000939,...,-0.001170,-0.030103,-0.016043,-0.008882,-0.016840,-0.021789,-0.006073,0.011973,-0.010155,-0.000521
Girl,0.011666,-0.000599,-0.022446,NaN,0.037102,0.006715,0.040237,0.038274,0.037856,0.002814,...,-0.001449,-0.048173,-0.021601,-0.002631,-0.020559,-0.037740,-0.032121,0.037098,-0.001679,-0.001493
Age 0,0.034664,-0.001217,0.001401,NaN,-0.115340,-0.002454,-0.109669,-0.115684,-0.117710,-0.001247,...,0.009147,0.033904,0.021651,0.015864,0.023622,0.032189,-0.003168,-0.115341,-0.017732,-0.001704
VICTIM COUNT,-0.002436,0.000716,-0.001063,NaN,0.001215,0.000599,0.001323,0.001271,0.001277,0.000274,...,1.000000,0.006930,-0.000268,-0.000504,0.009031,0.007259,-0.001779,0.001214,0.000011,0.000055
Accused Count,0.075759,-0.007032,-0.070931,NaN,-0.026402,-0.000852,-0.050132,-0.032503,-0.026408,0.000194,...,0.006930,1.000000,0.456484,0.249423,0.478704,0.751223,0.227127,-0.026413,-0.080568,-0.002721
Arrested Male,0.040951,-0.014406,-0.077284,NaN,-0.048350,0.005213,-0.038305,-0.042750,-0.046945,0.002433,...,-0.000268,0.456484,1.000000,0.224636,0.974281,0.623514,0.333703,-0.048362,-0.038988,0.001414
Arrested Female,0.017828,-0.015005,-0.032763,NaN,0.004210,0.003899,-0.018828,0.002774,0.004803,0.001027,...,-0.000504,0.249423,0.224636,1.000000,0.437321,0.246917,-0.037179,0.004205,-0.013119,-0.000018
Arrested Count\tNo.,0.041858,-0.016727,-0.078859,NaN,-0.043548,0.005716,-0.039581,-0.038711,-0.042115,0.002518,...,0.009031,0.478704,0.974281,0.437321,1.000000,0.632367,0.299240,-0.043559,-0.039065,0.001310
Accused_ChargeSheeted Count,0.065813,-0.007076,-0.055354,NaN,-0.032276,0.012572,-0.022651,-0.026020,-0.030439,0.001902,...,0.007259,0.751223,0.623514,0.246917,0.632367,1.000000,0.319453,-0.032283,-0.060151,-0.002994
Conviction Count,0.043650,-0.011510,-0.056386,NaN,-0.024698,0.003897,-0.005854,-0.017641,-0.022600,0.002619,...,-0.001779,0.227127,0.333703,-0.037179,0.299240,0.319453,1.000000,-0.024707,-0.026894,-0.002060
FIR_ID,-0.023674,0.006237,-0.050494,NaN,1.000000,-0.022457,0.954764,0.984092,0.992404,0.001452,...,0.001214,-0.026413,-0.048362,0.004205,-0.043559,-0.032283,-0.024707,1.000000,0.071857,0.000995
Unit_ID,-0.164605,0.011977,0.222597,NaN,0.071821,0.026059,0.070886,0.076497,0.074942,0.001964,...,0.000011,-0.080568,-0.038988,-0.013119,-0.039065,-0.060151,-0.026894,0.071857,1.000000,-0.021285
Crime_No,0.046801,-0.006954,0.007931,NaN,0.000963,0.014532,0.002695,0.002575,0.002973,0.000926,...,0.000055,-0.002721,0.001414,-0.000018,0.001310,-0.002994,-0.002060,0.000995,-0.021285,1.000000

In [83]:
df_clean_rows = df.dropna()

In [84]:
df_clean_columns = df.dropna(axis=1)

In [86]:
df

,District_Name,UnitName,FIRNo,Year,Month,Offence_From_Date,Offence_To_Date,FIR_Reg_DateTime,FIR_Date,FIR Type,...,VICTIM COUNT,Accused Count,Arrested Male,Arrested Female,Arrested Count\tNo.,Accused_ChargeSheeted Count,Conviction Count,FIR_ID,Unit_ID,Crime_No
0,0,26,0,2016,1,19614,9263,491,396,1,...,0,1,1,0,1,1,0,2016000002,1245,10470124520160001
1,0,26,9,2016,1,21598,12320,1338,1088,1,...,0,5,5,0,5,5,2,2016000003,1245,10470124520160002
2,0,26,18,2016,1,21600,12324,1341,1088,1,...,0,1,1,0,1,1,0,2016000004,1245,10470124520160003
3,0,26,27,2016,1,21887,12829,1652,1382,1,...,0,1,1,0,1,1,0,2016000005,1245,10470124520160004
4,0,26,36,2016,1,22374,13649,2025,1676,0,...,0,1,1,0,1,1,0,2016000006,1245,10470124520160005
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1694186,40,1038,17,2024,1,433115,701219,340512,998,1,...,0,0,0,0,0,0,0,2024000002,2183,10978218320240002
1694187,40,1038,26,2024,1,434559,703386,342490,2762,0,...,0,1,0,0,0,0,0,2024000003,2183,10978218320240003
1694188,40,1038,35,2024,2,437087,707596,343573,611,1,...,0,1,0,0,0,0,0,2024000004,2183,10978218320240004
1694189,40,1038,44,2024,2,438967,710756,345601,2281,0,...,0,5,0,0,0,0,0,2024000005,2183,10978218320240005
1694190,40,1038,53,2024,2,440081,712604,346099,2673,1,...,0,1,0,0,0,0,0,2024000006,2183,10978218320240006

In [87]:
df.columns

Index(['District_Name', 'UnitName', 'FIRNo', 'Year', 'Month',
       'Offence_From_Date', 'Offence_To_Date', 'FIR_Reg_DateTime', 'FIR_Date',
       'FIR Type', 'FIR_Stage', 'Complaint_Mode', 'CrimeGroup_Name',
       'CrimeHead_Name', 'Latitude', 'Longitude', 'ActSection', 'IOName',
       'KGID', 'IOAssigned_Date', 'Internal_IO', 'Place of Offence',
       'Distance from PS', 'Beat_Name', 'Village_Area_Name', 'Male', 'Female',
       'Boy', 'Girl', 'Age 0', 'VICTIM COUNT', 'Accused Count',
       'Arrested Male', 'Arrested Female', 'Arrested Count\tNo.',
       'Accused_ChargeSheeted Count', 'Conviction Count', 'FIR_ID', 'Unit_ID',
       'Crime_No'],
      dtype='object')

In [88]:
print(df['Beat_Name'].unique())

[5533 5545 5536 ... 2219 6701 6642]

In [89]:
print(df['VICTIM COUNT'].unique())

[ 0  1  8 16  2  3  6  5  4]

In [90]:
print(df['Accused_ChargeSheeted Count'].unique())

[  1   5   2   8  34  13  19  12   7  11  16   0   6   4  10   3   9  20
  15  24  14  21  23  17  25  22  39  26  18  31  28  27  29  49  36  44
  37  45  32  40  42  56  41  43  57  46  48  38  53  68  35  30  52  67
  33  51  79 116  58  74  55  65  50  77  69  64  54  85  59  72 196 293
  75  47 124  71 100 109  61 128  82  73  60  81  66  86 203 143  92  63
 160  70  89  98 105  78 102  87  80 155 107 115 139  84  94  90 154 330
  97  93 111  95 131  62 101 167  76 110 103 108 104  83 117  91 106 130
 133]

In [91]:
print(df['Conviction Count'].unique())

[ 0  2  1  9  4  5 11 15  7 10  8  3  6 12 19 13 14 18 16 21 20 40 24 28
 17 23 22 38 26 32 41 37 58 33 35 36 27 50 29 39 31 25 30 43 34 49 42 44
 74 45]

In [92]:
df = df.rename(columns={'Conviction Count': 'ConvictionCount'})

In [93]:
Y = df.ConvictionCount
X = df.iloc[:,[3,4,5,6,12,13,14,15,17,21,3,32,35,36]] 
X.head()

,Year,Month,Offence_From_Date,Offence_To_Date,CrimeGroup_Name,CrimeHead_Name,Latitude,Longitude,IOName,Place of Offence,Year,Arrested Male,Accused_ChargeSheeted Count,ConvictionCount
0,2016,1,19614,9263,86,351,0.0,0.0,15172,537660,2016,1,1,0
1,2016,1,21598,12320,66,437,0.0,0.0,4649,1113786,2016,5,5,2
2,2016,1,21600,12324,66,178,0.0,0.0,17622,1113770,2016,1,1,0
3,2016,1,21887,12829,73,285,0.0,0.0,15172,118514,2016,1,1,0
4,2016,1,22374,13649,72,350,0.0,0.0,8522,44940,2016,1,1,0

In [94]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.3,random_state=10)

In [95]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [97]:
from sklearn.linear_model import LogisticRegression
model_logr = LogisticRegression()
model_logr.fit(X_train,Y_train)

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').